config/README.md
config/data_sync_list/common.json
config/data_sync_list/ibm.json
config/data_sync_list/open-power.json
config/schema/example.json
config/schema/schema.json
meson.build
meson.options
scripts/run-ci.sh
scripts/validate_data_sync_list.py

The changes include :-
- Defines three JSON configuration files (common.json, open-power.json, and ibm.json) under config/data_sync_list.These files allow users to specify the files or directories to be synchronized between BMCs.
- Creates a schema file (config/schema/schema.json) for the above JSON configuration files, adhering to the Draft 2020-12 schema specification.
- Adds a Python script (scripts/validate_data_sync_list.py) to validate the JSON config files against the schema, along with another script (scripts/run-ci.sh) that triggers the validator during CI.
- Adds a new Meson build option (data_sync_list) where users can provide the list of JSON configuration files without .json file extension.
- Updates the Meson build system to install the specified JSON configuration files in …

data-sync: Adding data sync config files and validator

---

src/manager.cpp
src/manager.hpp

- Initiate events according to the data flow direction and synchronization type.
- All these events will run concurrently to simultaneously monitor and synchronize the data.

Manager: Start events concurrently to sync

---

config/schema/example.json
config/schema/schema.json
src/data_sync_config.cpp
src/data_sync_config.hpp
test/data_sync_config_test.cpp

- This optional property stores absolute path to target file/directory where files should be synced.
- This will enable syncing of files to a location different than the source, offering greater flexibility in file sync.
Tested:
- Verified the new JSON configuration
Change-Id: I5639126250ff12d6175045cebd1be9c19aceed5a

DataSync: Config: Added DestinationPath to configuration

---

src/manager.cpp
src/manager.hpp
test/meson.build

- Adding this API to help with future sync code testing.
- The added API uses rsync under the hood to perform a local copy for unit test verification, remote copy support will be added in a future commit.
- For testing we would require the data to be synced in same system. To enable it to have a compiler flag which would be used by test code.

Manager: Added API to sync data in UT environment

---

src/external_data_ifaces.cpp
src/external_data_ifaces.hpp
src/external_data_ifaces_impl.cpp
src/external_data_ifaces_impl.hpp
test/manager_test.cpp
test/mock_ext_data_ifaces.hpp

This PR includes the retrieval of the following external dependencies:
- Sibling BMC IP address
- RBMC credentials

ExternalData: Fetch required additional dependent data's

---

src/manager.cpp
test/manager_test.cpp
test/manager_test.hpp
test/meson.build
test/mock_ext_data_ifaces.hpp
test/periodic_sync_test.cpp

- Creating sync events that will become active in specified time.  It's aimed at optimizing synchronization for files and directories that do not require immediate updates.
- By scheduling sync events at regular intervals, we can better handle frequently updated data where real-time synchronization
isn't critical, such as audit logs and host console, will help to reduce load.
- Added utility functions to enable easy testing.
Tested:
- Verified the events are syncing data as required with 4 testcases:
- PeriodicDataSyncTest: Write but stops before sync interval therefore no sync could take place.
- PeriodicDataSyncDelayFileTest: Create a file after periodic sync is started, syncs new file after interval is passed.
- PeriodicDataSyncMultiRWTest: Write multi time and check for sync taking …

Manager: Create periodic events for sync process

---

service_files/xyz.openbmc_project.Control.SyncBMCData.service
src/meson.build
src/rbmc_data_sync_main.cpp

- As per community feedback, the previous BmcData interface is no longer agreed upon, Following the community's recommendation, this update migrates to the new SyncBmcData interface and folder structure
- The migration is aligned with the latest upstream changes, ensuring compatibility with the updated interface in phosphor-dbus-interfaces
- Reference: https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/76289

DataSync: Migrate to SyncBmcData interface

---

src/manager.cpp
src/manager.hpp
src/sync_bmc_data_ifaces.cpp
src/sync_bmc_data_ifaces.hpp
test/manager_test.cpp

- This commit provides implementation of disable sync DBus property.
- If disable is set to true, we restrict starting FullSync and stop all future background sync.
- If this property is set to false (i.e., sync enabled), we trigger sync events (immediate and periodic).
- Tested on simics.
~~This PR cannot get merged, before [PR168](https://github.com/ibm-openbmc/phosphor-dbus-interfaces/pull/168) for dbus-interfaces gets merged.~~
Change-Id: Ic7a6a63c1da74102405801d9e265c465f8a29af6

Manager: Implement Disable Sync property

---

src/manager.cpp
src/manager.hpp
src/sync_bmc_data_ifaces.cpp
test/full_sync_test.cpp
test/immediate_sync_test.cpp

- This commit provides implementation of sync events health property.
- If sync is disabled, we mark sync events health as 'Paused'.
- When full sync completes successfully we mark sync events health as 'Ok'.
- If any of sync events fails, we mark sync events health as 'Critical'.
- Modified test cases.
Tested
- Verified on simics.
Change-Id: Ic99f090f1023ad49b9492410d64fcb19ebf75513

Manager: Implement Sync Events Health property

---

src/manager.cpp
test/full_sync_test.cpp

- Force Full Sync to always report success, even if data sync fails
- Always set SyncEventsHealth to 'Ok' after sync attempt, regardless of success or failure
- This is a temporary change to unblock development and testing Will be reverted after proper error handling is implemented
Change-Id: I49d2eb48a078bb5301772678d4a8fb26cbea8b06

FullSync: Temporarily force Full Sync to always succeed

---

src/data_watcher.cpp

It is observed that while deleting the watching directories, it triggers the processing of IN_CREATE event also along with IN_DELETE_SELF processing which is not expected.
Root cause :
On analysis, it is figured out that delete operation of watching directories will emit IN_DELETE_SELF | IN_ISDIR which was passing the condition to invoke processCreate API also as it's check was mistakenly checking whether any of bits corresponds to IN_CREATE or IN_ISDIR set instead of checking both IN_CREATE and IN_ISDIR bit checking.
Solution :
Corrected the condition to invoke processCreate() with correct bit operations.
Tested :
- Verified in simics that no more processing of IN_CREATE events during deletion of watching directories.
Change-Id: I74ab7c59879567e915cee00cc47a7b4cd7364c9d

immediate-sync : Avoid the unwanted IN_CREATE event processing

---

src/manager.cpp
src/manager.hpp
src/meson.build
src/persistent.cpp
src/persistent.hpp
src/sync_bmc_data_ifaces.cpp
src/sync_bmc_data_ifaces.hpp
test/manager_test.cpp
test/manager_test.hpp
test/meson.build
test/persistent_data_test.cpp

- A JSON file was chosen so it's easy to see all the values at once and to capture them all in a dump or error log.
- Stores and Restores DBUS properties: 'FullSyncStatus', 'SyncEventsHealth' and 'DisableSync'
- Writes to the JSON whenever there's a change to above DBus properties.
- Design is compatible with introduction of new DBus properties.
Tested
- Added test cases.
- Verified on simics. Example JSON file generated:
```bash
$ cat /var/lib/phosphor-data-sync/persistence/dbus_props.json
{
"Disable": false,
"FullSyncStatus": 2,
"SyncEventsHealth": 2
}
```
Change-Id: Id6e2acb1b9b692e5925b9fcab61dec9eef6bbbff

DataSync: Added DBus Serialization Utilities

---

src/manager.cpp
test/full_sync_test.cpp
test/immediate_sync_test.cpp
test/manager_test.cpp
test/periodic_sync_test.cpp

This PR is dependent on the changes from [PR21](https://github.com/ibm-openbmc/phosphor-data-sync/pull/21) and is not merged yet.
Hence please review the below mentioned 2 commits as part of this PR :
1. [rsync-cli : Add --relative flag](https://github.com/ibm-openbmc/phosphor-data-sync/commit/59d18543ffc1d2d2432fa85e4f2f08be1775cb64)
2. [rsync-cli : Adding the necessary rsync flags](https://github.com/ibm-openbmc/phosphor-data-sync/commit/3299835bad5ec8e4a2aa7c39ad1c1303c727d728)

Enable the necessary rsync CLI options

---

src/data_sync_config.hpp
src/data_watcher.cpp
src/data_watcher.hpp
src/manager.cpp
src/manager.hpp

The commit modifies the syncData API which enables RSYNC to sync only the modified data path if available as SRC path instead of syncing the configured data path every time.
The change also modifies the file paths data type to std::filesystem::path for optimized performance.
Change-Id: Iac4bb9367ab84b34193e577999ae417ab38fe1e5

rsync : sync only the modified data path via Rsync

---

config/data_sync_list/common.json

The key to configure the exclude paths is changed from "ExcludeList" to "ExcludeFilesList and missed to update in the phosphor-fan-presence component so fixing the same
Change-Id: I2723d9fb90329b309bafb23beaeb3067933e2bb9

config: fan: Fix, update the exclude list key

---

config/data_sync_list/open-power.json

This commit adds '/var/lib/openpower-occ-control/' to the sync configuration to ensure OCC-related data is preserved across BMCs

config: Add sync config for OCC control data

---

config/data_sync_list/common.json

This commit adds '/var/log/obmc-console.log' and '/var/log/ obmc-console1.log' to the sync configuration to ensure host boot and IPL logs are available on both BMCs
These files capture critical boot-related logs, including SBE and Hostboot (PHYP and OS) istep data. Syncing them helps preserve historical context of host boot attempts, which is useful for debugging, especially after a BMC failover

config: Add sync config for host console log files

---

src/data_sync_config.cpp

This commit introduces a change to resolve symlink paths to their actual target path

DataSync: Handle symlink paths by resolving to target path

---

src/data_watcher.cpp
src/data_watcher.hpp
src/manager.cpp
test/immediate_sync_test.cpp

This PR commits is dependent on PR21 and PR26 , which are yet to merge and contains the commits from PR21 and PR26 also. Hence review the below mentioned commits.
1. [inotify : process the IN_MOVED_TO signal](https://github.com/ibm-openbmc/phosphor-data-sync/commit/3adad6cce423c2ec2dd3696305897aa12c1add9d)
2. [inotify : Process IN_MOVED_FROM signal](https://github.com/ibm-openbmc/phosphor-data-sync/commit/feec13e889cd496a1d1c28f4369b452e89fa50eb)
3. [inotify : Watch for IN_MOVED_FROM and IN_MOVED_TO signals](https://github.com/ibm-openbmc/phosphor-data-sync/commit/8bf67403377ec8c3a79969b3f2e201de0b3f0017)

Add the support to handle IN_MOVED_TO and IN_MOVED_FROM inotify events

---

src/data_watcher.cpp
src/data_watcher.hpp
test/immediate_sync_test.cpp

- During bidirectional sync operations, rsync creates hidden temporary files at the destination before renaming them to their final names. This results in:
- IN_MOVED_FROM events for the hidden temporary files.
- IN_MOVED_TO events for the actual target files.
- The IN_MOVED_FROM events from hidden files were ignored, and IN_MOVED_TO events would trigger another sync, potentially causing unnecessary operations.
Hence this commit introduces the following changes:
- Temporarily store all IN_MOVED_FROM events.
- Only process IN_MOVED_TO events if the corresponding IN_MOVED_FROM was from a non-hidden file.
- Ignore processing IN_MOVED_FROM events that originate from hidden temporary files created by rsync.
- This ensures that sync is triggered only for genuine file moves and avoids redundant …

inotify : Avoid unnecessary rsync during bidirectional sync

---

config/data_sync_list/open-power.json

This commit adds '/var/lib/op-hw-isolation/persistdata/' to the sync configuration to ensure hardware isolation state is preserved across BMCs
The directory is synced immediately from the active to the passive BMC to maintain the data on both bmc

config: Add sync config for hardware isolation data

---

config/data_sync_list/open-power.json

This commit adds '/var/lib/phal/' to the sync configuration to ensure PHAL-related state data is available on both BMCs
The directory is synced immediately from the active to the passive BMC

config: Add sync config for PHAL persisted data

---

config/data_sync_list/open-power.json

This commit adds '/var/lib/network/hypervisor/' to the sync configuration to ensure host virtual management interface (VMI) data is preserved across BMC
The directory is synced immediately from the active to the passive BMC to retain consistent network configuration state after a failover

config: Add sync config for host VMI data

---

config/data_sync_list/open-power.json

This commit adds the PHYP-NVRAM file from '/var/lib/phosphor- software-manager/hostfw/nvram/' to the sync configuration to ensure PHYP-specific NVRAM data is preserved across BMC
The file is synced immediately from the active to the passive BMC

config: Add sync config for PHYP NVRAM data

---

config/data_sync_list/open-power.json

This commit adds the PHYP-NVRAM-CKSUM file from '/var/lib/phosphor -software-manager/hostfw/nvram/' to the sync configuration to ensure the checksum data associated with PHYP NVRAM is preserved across BMC
The file is synced immediately from the active to the passive BMC

config: Add sync config for PHYP NVRAM checksum data

---

config/data_sync_list/open-power.json

This commit adds the EECACHE file from '/var/lib/phosphor- software-manager/hostfw/running/' to the sync configuration to ensure host owned VPD cache data is preserved across BMC
EECACHE is maintained by Hostboot and contains a cached view of the VPD EEPROM, Since this data is shared across both BMC, it must be kept in sync to ensure consistency regardless of which BMC is active

config: Add sync config for host owned VPD cache

---

config/data_sync_list/open-power.json

This commit adds the NVRAM file from '/var/lib/phosphor-software -manager/hostfw/running/' to the sync configuration to ensure host OPAL NVRAM data is preserved across BMC
This data is used by OPAL, particularly in manufacturing and must be kept in sync
The file is synced immediately from the active to the passive BMC

config: Add sync config for host NVRAM data

---

config/data_sync_list/ibm.json

This commit add '/var/lib/bmcweb/ibm-management-console/configfiles/' to the sync configuration to ensure host-side saved config data is preserved across BMC
The directory is synced immediately from active to passive

config: Add sync config for host save area config files

---

config/data_sync_list/common.json

This commit adds '/var/lib/phosphor-inventory-manager/' to the sync configuration to ensure system inventory data is preserved across BMC
The data is synced immediately from the active to the passive BMC to retain inventory state. However, the sync destination on the passive side is set to '/var/lib/phosphor-data-sync/bmc_data_bkp/' to avoid triggering inventory publication on DBus during passive BMC reboot

config: Add sync config for system inventory data

---

config/data_sync_list/common.json

This commit adds '/var/lib/phosphor-state-manager/' to the sync configuration to preserve system state information across BMC
The directory is synced immediately from the active to the passive The following files are excluded:
• requestedHostTransition — no longer used
• POHCounter — no longer used
• chassisStateChangeTime — no longer used

config: Add sync config for system state manager data

---

config/data_sync_list/common.json

Added '/var/lib/service-config-manager/' to the sync list to make sure service enable/disable state is preserved across BMC
The data is synced immediately from active to passive BMC

config: Add sync config for service manager data

---

src/async_command_exec.cpp
src/async_command_exec.hpp
src/data_watcher.hpp
src/manager.cpp
src/meson.build
src/utility.cpp
src/utility.hpp
test/full_sync_test.cpp
test/immediate_sync_test.cpp
test/manager_test.cpp
test/manager_test.hpp
test/periodic_sync_test.cpp
test/persistent_data_test.cpp

This commit introduces the changes to replace the `std::system` with `posix_spawn` for the execution of RSYNC CLI in order to achieve the asynchronous execution of multiple RSYNC commands.
Reasons for moving to posix_spawn():
- The `std::system()` is a blocking call where it hold until the command finishes execution which is achieving asynchronous behavior.
- `std::system()` lacks the method to capture the output of the execution to the parent/caller and the return value of the execution which results in limited error handling.
- `posix_spawn` enables launching child processes without blocking the main thread.
- `posix_spawn_file_actions` allows fine-grained control of fd redirection, useful for isolating command input/output.
Details of implementation:
- The API `execCmd()` invokes …

Replace `std::system` with `posix_spawn` for async execution
